/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BroadcastsRouteImport } from './routes/broadcasts'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EsignRouteImport } from './routes/esign'
import { Route as FilesRouteImport } from './routes/files'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FloorplansRouteImport } from './routes/floorplans'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as GigsRouteImport } from './routes/gigs'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeadboosterRouteImport } from './routes/leadbooster'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as MailRouteImport } from './routes/mail'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProspectorRouteImport } from './routes/prospector'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SequencesRouteImport } from './routes/sequences'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as BoardTokenRouteImport } from './routes/board.$token'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as CalTokenRouteImport } from './routes/cal.$token'
import { Route as ContactsPersonIdRouteImport } from './routes/contacts.$personId'
import { Route as DealsDealIdRouteImport } from './routes/deals.$dealId'
import { Route as EsignEnvelopeIdRouteImport } from './routes/esign.$envelopeId'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as OrgsOrgIdRouteImport } from './routes/orgs.$orgId'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as SignDocIdRouteImport } from './routes/sign.$docId'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastsRoute = BroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EsignRoute = EsignRouteImport.update({
  id: '/esign',
  path: '/esign',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorplansRoute = FloorplansRouteImport.update({
  id: '/floorplans',
  path: '/floorplans',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsRoute = GigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadboosterRoute = LeadboosterRouteImport.update({
  id: '/leadbooster',
  path: '/leadbooster',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectorRoute = ProspectorRouteImport.update({
  id: '/prospector',
  path: '/prospector',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SequencesRoute = SequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardTokenRoute = BoardTokenRouteImport.update({
  id: '/board/$token',
  path: '/board/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalTokenRoute = CalTokenRouteImport.update({
  id: '/cal/$token',
  path: '/cal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsPersonIdRoute = ContactsPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => ContactsRoute,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const EsignEnvelopeIdRoute = EsignEnvelopeIdRouteImport.update({
  id: '/$envelopeId',
  path: '/$envelopeId',
  getParentRoute: () => EsignRoute,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdRoute = OrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignDocIdRoute = SignDocIdRouteImport.update({
  id: '/sign/$docId',
  path: '/sign/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/boards': typeof BoardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/broadcasts': typeof BroadcastsRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/crew': typeof CrewRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/documents': typeof DocumentsRoute
  '/esign': typeof EsignRouteWithChildren
  '/files': typeof FilesRoute
  '/finance': typeof FinanceRoute
  '/floorplans': typeof FloorplansRoute
  '/forecast': typeof ForecastRoute
  '/forgot': typeof ForgotRoute
  '/forms': typeof FormsRoute
  '/gigs': typeof GigsRoute
  '/goals': typeof GoalsRoute
  '/guests': typeof GuestsRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/leadbooster': typeof LeadboosterRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/marketplace': typeof MarketplaceRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRoute
  '/prospector': typeof ProspectorRoute
  '/pulse': typeof PulseRoute
  '/quotes': typeof QuotesRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/board/$token': typeof BoardTokenRoute
  '/book/$slug': typeof BookSlugRoute
  '/cal/$token': typeof CalTokenRoute
  '/contacts/$personId': typeof ContactsPersonIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/esign/$envelopeId': typeof EsignEnvelopeIdRoute
  '/f/$slug': typeof FSlugRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/p/$token': typeof PTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sign/$docId': typeof SignDocIdRoute
  '/w/$slug': typeof WSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/boards': typeof BoardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/broadcasts': typeof BroadcastsRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/crew': typeof CrewRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/documents': typeof DocumentsRoute
  '/esign': typeof EsignRouteWithChildren
  '/files': typeof FilesRoute
  '/finance': typeof FinanceRoute
  '/floorplans': typeof FloorplansRoute
  '/forecast': typeof ForecastRoute
  '/forgot': typeof ForgotRoute
  '/forms': typeof FormsRoute
  '/gigs': typeof GigsRoute
  '/goals': typeof GoalsRoute
  '/guests': typeof GuestsRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/leadbooster': typeof LeadboosterRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/marketplace': typeof MarketplaceRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRoute
  '/prospector': typeof ProspectorRoute
  '/pulse': typeof PulseRoute
  '/quotes': typeof QuotesRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/board/$token': typeof BoardTokenRoute
  '/book/$slug': typeof BookSlugRoute
  '/cal/$token': typeof CalTokenRoute
  '/contacts/$personId': typeof ContactsPersonIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/esign/$envelopeId': typeof EsignEnvelopeIdRoute
  '/f/$slug': typeof FSlugRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/p/$token': typeof PTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sign/$docId': typeof SignDocIdRoute
  '/w/$slug': typeof WSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/automations': typeof AutomationsRoute
  '/boards': typeof BoardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/broadcasts': typeof BroadcastsRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/crew': typeof CrewRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/documents': typeof DocumentsRoute
  '/esign': typeof EsignRouteWithChildren
  '/files': typeof FilesRoute
  '/finance': typeof FinanceRoute
  '/floorplans': typeof FloorplansRoute
  '/forecast': typeof ForecastRoute
  '/forgot': typeof ForgotRoute
  '/forms': typeof FormsRoute
  '/gigs': typeof GigsRoute
  '/goals': typeof GoalsRoute
  '/guests': typeof GuestsRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/inbox': typeof InboxRoute
  '/insights': typeof InsightsRoute
  '/integrations': typeof IntegrationsRoute
  '/leadbooster': typeof LeadboosterRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/mail': typeof MailRoute
  '/marketplace': typeof MarketplaceRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRoute
  '/prospector': typeof ProspectorRoute
  '/pulse': typeof PulseRoute
  '/quotes': typeof QuotesRoute
  '/request': typeof RequestRoute
  '/reviews': typeof ReviewsRoute
  '/sandbox': typeof SandboxRoute
  '/scheduler': typeof SchedulerRoute
  '/security': typeof SecurityRoute
  '/sequences': typeof SequencesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/travel': typeof TravelRoute
  '/board/$token': typeof BoardTokenRoute
  '/book/$slug': typeof BookSlugRoute
  '/cal/$token': typeof CalTokenRoute
  '/contacts/$personId': typeof ContactsPersonIdRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/esign/$envelopeId': typeof EsignEnvelopeIdRoute
  '/f/$slug': typeof FSlugRoute
  '/orgs/$orgId': typeof OrgsOrgIdRoute
  '/p/$token': typeof PTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sign/$docId': typeof SignDocIdRoute
  '/w/$slug': typeof WSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai'
    | '/approvals'
    | '/automations'
    | '/boards'
    | '/bookmarks'
    | '/broadcasts'
    | '/chatbot'
    | '/contact'
    | '/contacts'
    | '/crew'
    | '/developers'
    | '/discover'
    | '/documents'
    | '/esign'
    | '/files'
    | '/finance'
    | '/floorplans'
    | '/forecast'
    | '/forgot'
    | '/forms'
    | '/gigs'
    | '/goals'
    | '/guests'
    | '/handoff'
    | '/health'
    | '/home'
    | '/import'
    | '/inbox'
    | '/insights'
    | '/integrations'
    | '/leadbooster'
    | '/leads'
    | '/login'
    | '/lookup'
    | '/mail'
    | '/marketplace'
    | '/products'
    | '/profile'
    | '/projects'
    | '/proposals'
    | '/prospector'
    | '/pulse'
    | '/quotes'
    | '/request'
    | '/reviews'
    | '/sandbox'
    | '/scheduler'
    | '/security'
    | '/sequences'
    | '/settings'
    | '/tasks'
    | '/travel'
    | '/board/$token'
    | '/book/$slug'
    | '/cal/$token'
    | '/contacts/$personId'
    | '/deals/$dealId'
    | '/esign/$envelopeId'
    | '/f/$slug'
    | '/orgs/$orgId'
    | '/p/$token'
    | '/projects/$projectId'
    | '/rsvp/$token'
    | '/sign/$docId'
    | '/w/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/admin'
    | '/ai'
    | '/approvals'
    | '/automations'
    | '/boards'
    | '/bookmarks'
    | '/broadcasts'
    | '/chatbot'
    | '/contact'
    | '/contacts'
    | '/crew'
    | '/developers'
    | '/discover'
    | '/documents'
    | '/esign'
    | '/files'
    | '/finance'
    | '/floorplans'
    | '/forecast'
    | '/forgot'
    | '/forms'
    | '/gigs'
    | '/goals'
    | '/guests'
    | '/handoff'
    | '/health'
    | '/home'
    | '/import'
    | '/inbox'
    | '/insights'
    | '/integrations'
    | '/leadbooster'
    | '/leads'
    | '/login'
    | '/lookup'
    | '/mail'
    | '/marketplace'
    | '/products'
    | '/profile'
    | '/projects'
    | '/proposals'
    | '/prospector'
    | '/pulse'
    | '/quotes'
    | '/request'
    | '/reviews'
    | '/sandbox'
    | '/scheduler'
    | '/security'
    | '/sequences'
    | '/settings'
    | '/tasks'
    | '/travel'
    | '/board/$token'
    | '/book/$slug'
    | '/cal/$token'
    | '/contacts/$personId'
    | '/deals/$dealId'
    | '/esign/$envelopeId'
    | '/f/$slug'
    | '/orgs/$orgId'
    | '/p/$token'
    | '/projects/$projectId'
    | '/rsvp/$token'
    | '/sign/$docId'
    | '/w/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/admin'
    | '/ai'
    | '/approvals'
    | '/automations'
    | '/boards'
    | '/bookmarks'
    | '/broadcasts'
    | '/chatbot'
    | '/contact'
    | '/contacts'
    | '/crew'
    | '/developers'
    | '/discover'
    | '/documents'
    | '/esign'
    | '/files'
    | '/finance'
    | '/floorplans'
    | '/forecast'
    | '/forgot'
    | '/forms'
    | '/gigs'
    | '/goals'
    | '/guests'
    | '/handoff'
    | '/health'
    | '/home'
    | '/import'
    | '/inbox'
    | '/insights'
    | '/integrations'
    | '/leadbooster'
    | '/leads'
    | '/login'
    | '/lookup'
    | '/mail'
    | '/marketplace'
    | '/products'
    | '/profile'
    | '/projects'
    | '/proposals'
    | '/prospector'
    | '/pulse'
    | '/quotes'
    | '/request'
    | '/reviews'
    | '/sandbox'
    | '/scheduler'
    | '/security'
    | '/sequences'
    | '/settings'
    | '/tasks'
    | '/travel'
    | '/board/$token'
    | '/book/$slug'
    | '/cal/$token'
    | '/contacts/$personId'
    | '/deals/$dealId'
    | '/esign/$envelopeId'
    | '/f/$slug'
    | '/orgs/$orgId'
    | '/p/$token'
    | '/projects/$projectId'
    | '/rsvp/$token'
    | '/sign/$docId'
    | '/w/$slug'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationsRoute: typeof AutomationsRoute
  BoardsRoute: typeof BoardsRoute
  BookmarksRoute: typeof BookmarksRoute
  BroadcastsRoute: typeof BroadcastsRoute
  ChatbotRoute: typeof ChatbotRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  CrewRoute: typeof CrewRoute
  DevelopersRoute: typeof DevelopersRoute
  DiscoverRoute: typeof DiscoverRoute
  DocumentsRoute: typeof DocumentsRoute
  EsignRoute: typeof EsignRouteWithChildren
  FilesRoute: typeof FilesRoute
  FinanceRoute: typeof FinanceRoute
  FloorplansRoute: typeof FloorplansRoute
  ForecastRoute: typeof ForecastRoute
  ForgotRoute: typeof ForgotRoute
  FormsRoute: typeof FormsRoute
  GigsRoute: typeof GigsRoute
  GoalsRoute: typeof GoalsRoute
  GuestsRoute: typeof GuestsRoute
  HandoffRoute: typeof HandoffRoute
  HealthRoute: typeof HealthRoute
  HomeRoute: typeof HomeRoute
  ImportRoute: typeof ImportRoute
  InboxRoute: typeof InboxRoute
  InsightsRoute: typeof InsightsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeadboosterRoute: typeof LeadboosterRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  MailRoute: typeof MailRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ProposalsRoute: typeof ProposalsRoute
  ProspectorRoute: typeof ProspectorRoute
  PulseRoute: typeof PulseRoute
  QuotesRoute: typeof QuotesRoute
  RequestRoute: typeof RequestRoute
  ReviewsRoute: typeof ReviewsRoute
  SandboxRoute: typeof SandboxRoute
  SchedulerRoute: typeof SchedulerRoute
  SecurityRoute: typeof SecurityRoute
  SequencesRoute: typeof SequencesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TravelRoute: typeof TravelRoute
  BoardTokenRoute: typeof BoardTokenRoute
  BookSlugRoute: typeof BookSlugRoute
  CalTokenRoute: typeof CalTokenRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  FSlugRoute: typeof FSlugRoute
  OrgsOrgIdRoute: typeof OrgsOrgIdRoute
  PTokenRoute: typeof PTokenRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  SignDocIdRoute: typeof SignDocIdRoute
  WSlugRoute: typeof WSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcasts': {
      id: '/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof BroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esign': {
      id: '/esign'
      path: '/esign'
      fullPath: '/esign'
      preLoaderRoute: typeof EsignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floorplans': {
      id: '/floorplans'
      path: '/floorplans'
      fullPath: '/floorplans'
      preLoaderRoute: typeof FloorplansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs': {
      id: '/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof GigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadbooster': {
      id: '/leadbooster'
      path: '/leadbooster'
      fullPath: '/leadbooster'
      preLoaderRoute: typeof LeadboosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospector': {
      id: '/prospector'
      path: '/prospector'
      fullPath: '/prospector'
      preLoaderRoute: typeof ProspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sequences': {
      id: '/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof SequencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$token': {
      id: '/board/$token'
      path: '/board/$token'
      fullPath: '/board/$token'
      preLoaderRoute: typeof BoardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cal/$token': {
      id: '/cal/$token'
      path: '/cal/$token'
      fullPath: '/cal/$token'
      preLoaderRoute: typeof CalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$personId': {
      id: '/contacts/$personId'
      path: '/$personId'
      fullPath: '/contacts/$personId'
      preLoaderRoute: typeof ContactsPersonIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esign/$envelopeId': {
      id: '/esign/$envelopeId'
      path: '/$envelopeId'
      fullPath: '/esign/$envelopeId'
      preLoaderRoute: typeof EsignEnvelopeIdRouteImport
      parentRoute: typeof EsignRoute
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId': {
      id: '/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$docId': {
      id: '/sign/$docId'
      path: '/sign/$docId'
      fullPath: '/sign/$docId'
      preLoaderRoute: typeof SignDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContactsRouteChildren {
  ContactsPersonIdRoute: typeof ContactsPersonIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsPersonIdRoute: ContactsPersonIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface EsignRouteChildren {
  EsignEnvelopeIdRoute: typeof EsignEnvelopeIdRoute
}

const EsignRouteChildren: EsignRouteChildren = {
  EsignEnvelopeIdRoute: EsignEnvelopeIdRoute,
}

const EsignRouteWithChildren = EsignRoute._addFileChildren(EsignRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationsRoute: AutomationsRoute,
  BoardsRoute: BoardsRoute,
  BookmarksRoute: BookmarksRoute,
  BroadcastsRoute: BroadcastsRoute,
  ChatbotRoute: ChatbotRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRouteWithChildren,
  CrewRoute: CrewRoute,
  DevelopersRoute: DevelopersRoute,
  DiscoverRoute: DiscoverRoute,
  DocumentsRoute: DocumentsRoute,
  EsignRoute: EsignRouteWithChildren,
  FilesRoute: FilesRoute,
  FinanceRoute: FinanceRoute,
  FloorplansRoute: FloorplansRoute,
  ForecastRoute: ForecastRoute,
  ForgotRoute: ForgotRoute,
  FormsRoute: FormsRoute,
  GigsRoute: GigsRoute,
  GoalsRoute: GoalsRoute,
  GuestsRoute: GuestsRoute,
  HandoffRoute: HandoffRoute,
  HealthRoute: HealthRoute,
  HomeRoute: HomeRoute,
  ImportRoute: ImportRoute,
  InboxRoute: InboxRoute,
  InsightsRoute: InsightsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeadboosterRoute: LeadboosterRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  MailRoute: MailRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ProposalsRoute: ProposalsRoute,
  ProspectorRoute: ProspectorRoute,
  PulseRoute: PulseRoute,
  QuotesRoute: QuotesRoute,
  RequestRoute: RequestRoute,
  ReviewsRoute: ReviewsRoute,
  SandboxRoute: SandboxRoute,
  SchedulerRoute: SchedulerRoute,
  SecurityRoute: SecurityRoute,
  SequencesRoute: SequencesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TravelRoute: TravelRoute,
  BoardTokenRoute: BoardTokenRoute,
  BookSlugRoute: BookSlugRoute,
  CalTokenRoute: CalTokenRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  FSlugRoute: FSlugRoute,
  OrgsOrgIdRoute: OrgsOrgIdRoute,
  PTokenRoute: PTokenRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  SignDocIdRoute: SignDocIdRoute,
  WSlugRoute: WSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
